# Generated by Django 4.2 on 2023-04-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valo_ask_rasskazov', '0002_answer_text_question_creator_alter_question_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='summary_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
